
//Builds Data Actions 

export const FETCH_TRANSACTION_DATA = 'fetchTransactionDetails';
export const CLAM_AV_VIRUS_REPORT_SUCCESS = 'CLAM_AV_VIRUS_REPORT_SUCCESS';

export const CLAM_AV_REPORT_DATES = 'CLAM_AV_REPORT_DATES';

export const CLAM_AV_REPORT_PASSED = 'CLAM_AV_REPORT_PASSED';
export const CLAM_AV_REPORT_INFECTED = 'CLAM_AV_REPORT_INFECTED';
export const CLAM_AV_REPORT_WARNING = 'CLAM_AV_REPORT_WARNING';
export const CLAM_AV_REPORT_SCANNED_DIRECTORIES = 'CLAM_AV_REPORT_SCANNED_DIRECTORIES';


export const BLACK_DUCK_VIRUS_REPORT_SUCCESS = 'BLACK_DUCK_VIRUS_REPORT_SUCCESS';


export const BLACK_DUCK_REPORT_DATES = 'BLACK_DUCK_REPORT_DATES';

export const BLACK_DUCK_REPORT_HIGH = 'BLACK_DUCK_REPORT_HIGH';
export const BLACK_DUCK_REPORT_LOW = 'BLACK_DUCK_REPORT_LOW';
export const BLACK_DUCK_REPORT_MEDIUM = 'BLACK_DUCK_REPORT_MEDIUM';
export const BLACK_DUCK_REPORT_NONE = 'BLACK_DUCK_REPORT_NONE';

export const FOSS_VULNERABLE_REPORT_SUCCESS = 'FOSS_VULNERABLE_REPORT_SUCCESS';

export const SURFACE_ANALYSIS_REPORT_SUCCESS = 'SURFACE_ANALYSIS_REPORT_SUCCESS';

export const SURFACE_ANALYSIS_REPORT_DATES = 'SURFACE_ANALYSIS_REPORT_DATES';

export const SURFACE_ANALYSIS_REPORT_TOTAL_SCANNED = 'SURFACE_ANALYSIS_REPORT_TOTAL_SCANNED';

export const SURFACE_ANALYSIS_REPORT_UP_STATE = 'SURFACE_ANALYSIS_REPORT_UP_STATE';

export const SURFACE_ANALYSIS_REPORT_DOWN_STATE = 'SURFACE_ANALYSIS_REPORT_DOWN_STATE';

export const FOSS_VULNERABLE_REPORT_DATES = 'FOSS_VULNERABLE_REPORT_DATES';

export const FOSS_VULNERABLE_REPORT_ACTUALNUMPACKAGE = 'FOSS_VULNERABLE_REPORT_ACTUALNUMPACKAGE';

export const FOSS_VULNERABLE_REPORT_TOTALVULPACKAGE = 'FOSS_VULNERABLE_REPORT_TOTALVULPACKAGE';

export const FOSS_VULNERABLE_REPORT_CRITICAL_SEVERITY = 'FOSS_VULNERABLE_REPORT_CRITICAL_SEVERITY';

export const FOSS_VULNERABLE_REPORT_HIGH_SEVERITY = 'FOSS_VULNERABLE_REPORT_HIGH_SEVERITY';

export const FOSS_VULNERABLE_REPORT_MEDIUM_SEVERITY = 'FOSS_VULNERABLE_REPORT_MEDIUM_SEVERITY';

export const FOSS_VULNERABLE_REPORT_LOW_SEVERITY = 'FOSS_VULNERABLE_REPORT_LOW_SEVERITY';